// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMHq2szDwYRR_GS0OFljh2Z6xfheXSTM',
    appId: '1:931751344368:web:f401e836637e24bea4ea35',
    messagingSenderId: '931751344368',
    projectId: 'kyarem-sports',
    authDomain: 'kyarem-sports.firebaseapp.com',
    storageBucket: 'kyarem-sports.firebasestorage.app',
    measurementId: 'G-VVRFH4YH03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAPgSfSRIwYGQHGqiCVXt8wvMTvW-nB6g',
    appId: '1:969066450645:android:7a4d0f0334bdfbd81f5c5c',
    messagingSenderId: '969066450645',
    projectId: 'kyarem-b31de',
    storageBucket: 'kyarem-b31de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUPOTyqQlDM7yWv6VwnP19D7Tu4zv9siI',
    appId: '1:969066450645:ios:eb4b95c3f9be97d21f5c5c',
    messagingSenderId: '969066450645',
    projectId: 'kyarem-b31de',
    storageBucket: 'kyarem-b31de.firebasestorage.app',
    iosBundleId: 'com.example.appArbitro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkuH_ZLSAkqUdYGKaW4zxSwGMiyWubNq4',
    appId: '1:931751344368:ios:666fdc10ad0b8704a4ea35',
    messagingSenderId: '931751344368',
    projectId: 'kyarem-sports',
    storageBucket: 'kyarem-sports.firebasestorage.app',
    iosBundleId: 'com.example.appArbitro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMHq2szDwYRR_GS0OFljh2Z6xfheXSTM',
    appId: '1:931751344368:web:ccb71a2a8329de35a4ea35',
    messagingSenderId: '931751344368',
    projectId: 'kyarem-sports',
    authDomain: 'kyarem-sports.firebaseapp.com',
    storageBucket: 'kyarem-sports.firebasestorage.app',
    measurementId: 'G-NDDSGB3W7G',
  );
}
